### ISSUE TITLE
The login page

### ISSUE THREAD

**Issue by yo1995** [DukeLearningInnovation/sakai-mobile-ios#4]
Currently the login page uses a UIWebView.

A potential Swift native solution is here: https://github.com/OpenClemson/SwiftECP

If we stick to WebView, a better logic and looking should be implemented. I found many apps, such as OneDrive and EAccounts (RFC card manager) have their own implementation of log in page.

OneDrive use a webview. after you key in the netid, it automatically dismiss, and add a progress indicator overlay until it loads.

EAccounts seems to use some API of Duke, but most of the time is buggy and pop up error messages.

**Comment by yo1995** [comment]
By checking the DukeMobile app, I found they used an API: https://mobile-authorizer.oit.duke.edu/dukemobile/ios/callback to login some pages. I don't know if there exists such API for Sakai or universal authentication.

**Comment by yo1995** [comment]
The good news is, I figure out the correct (at least working) way of using WKWebView to go through the Shib auth and fetch data from API.

| OneDrive | Current DukeSakai with `UIWebView` |
|:---:|:---:|
|![OneDrive](https://user-images.githubusercontent.com/9660181/59555331-71d5d080-8f7e-11e9-8cd4-c050901aeef8.gif)|![DukeSakai](https://user-images.githubusercontent.com/9660181/59555330-71d5d080-8f7e-11e9-944d-f0e56369d03f.gif)|

| Mine with `WKWebView` with progress spinner| iPad with `.formSheet`|
|:---:|:---:|
|![authpage-v2](https://user-images.githubusercontent.com/9660181/59556260-8d94a300-8f8d-11e9-9dfd-4dbada162080.gif)|![iPad-demo](https://user-images.githubusercontent.com/9660181/59556261-908f9380-8f8d-11e9-93c6-7d3940f52e32.gif)|

Above is a brief demo of this webView auth method, pretty much the same as OneDrive.

Also, included some comparison.

**Comment by yo1995** [comment]
What make it even more impossible to make a native login page is the Duo Mobile auth step.

If there are only username and password, it is doable to create a proxy layer UI in Swift, and run a headless WKWebView to go through the process;

But if we have the Duo step, we have to figure out how it interact with Shib, and how it reflects in the auth, e.g. token, secret key, etc.

**Comment by AndresHernandezGuerra** [comment]
What would be the benefit of using WKWebView as opposed to the current login page? I feel like the look and functionality of the current one is much simpler and easy to use.

And you are right, what makes is very hard to make a native login screen is the multi factor authentication. I looked at how OneDrive does their login and it’s actually worse than how we do it currently (adds extra steps to the login process). What we could definitely do is add the progress indicator, which can be helpful 👍🏽!

**Comment by yo1995** [comment]
> What would be the benefit of using WKWebView as opposed to the current login page? I feel like the look and functionality of the current one is much simpler and easy to use.
> 
> And you are right, what makes is very hard to make a native login screen is the multi factor authentication. I looked at how OneDrive does their login and it’s actually worse than how we do it currently (adds extra steps to the login process). What we could definitely do is add the progress indicator, which can be helpful 👍🏽!

I saw [`UIWebView`](https://developer.apple.com/documentation/uikit/uiwebview) is deprecated by Apple from iOS12, and also it consumes more memory than `WKWebView`. Therefore I thought creating a new version in WKWebView is useful.

**Comment by yo1995** [comment]
One more thing to mention:
During the login auth & redirect process, 3 redirects and 4+ navigations happens. 

In the previous method below,
```swift
if !((loginWebView.request?.url?.absoluteString.hasPrefix("https://sakai.duke.edu/portal"))! ){
    return
}
```

It checks the prefix of url as the condition. Whereas it works, I plan to make it more precise later on.

**Comment by yo1995** [comment]
Maybe we can preserve the login status, so that user won't need to login every time when he re-launch the app? Not sure about this idea yet.

Also, when I check the code after login step, I found they all used the `URLSession.shared` session to make requests. In this way, it would be relatively huge work to migrate to `WKWebView` - adapt every request to the new version. Therefore, I won't try to integrate this issue to current codebase, and will talk with Prof. Ric about his idea.

**Comment by yo1995** [comment]
More to update after today discussion with Prof. Ric... 🤔

---
190617

After discussing with Prof., I'll create a new branch and insert the new WKWebView in there, and try to clean up other parts. The new branch will be called `new-login`

**Comment by yo1995** [comment]
@mpellicer @profmikegreene Sorry to ask again, but it seems I do not have the correct permission to contribute to this repo. 😅 Could you grant me the correct one?

I'm not familiar with the permissions with GitHub, does it have a GitLab `developer` level of permission that allow me to push to the repo except for `master` branch?

@profRic If you still use GitHub account, you can check the progress for DukeSakai in this repo.

Thanks.

**Comment by yo1995** [comment]
Hi all,
I've embedded the new WKWebView login page to the project under `new-login` branch. Feel free to test it out.

**Comment by profmikegreene** [comment]
@yo1995 I take that to team your permissions are configured the way you need now?

**Comment by yo1995** [comment]
> @yo1995 I take that to team your permissions are configured the way you need now?

Yes! I can now push to the repo. Thanks.
